version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - db

  php:
    container_name: php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - nginx
    restart: always

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: